region           = "ca-central-1"
environment      = "learning"
sqs_queue_name   = "harita-testpulse-ingestion-queue"
s3_bucket_name   = "harita-testpulse-raw-2026"
lambda_role_name = "harita-testpulse-lambda-role"
ec2_role_name    = "harita-testpulse-ec2-role"